[world]
kind = "WorldContract"
class_hash = "0xf6f44afb3cacbcc01a371aff62c86ca9a45feba065424c99f7cd8637514d8f"
original_class_hash = "0xf6f44afb3cacbcc01a371aff62c86ca9a45feba065424c99f7cd8637514d8f"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x3685b56189052cadc904dbc808087089234e0e8ed41d0957790f381e5f3c1bf"
transaction_hash = "0x762ef4da956b2cabca9f00fc596bb76e9d73b1564b8abbdd2a56db6bd525409"
block_number = 3
seed = "master_mind"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://0.0.0.0:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x118d0e4e009489c32db5a55e75bf614d655624a2942ced6cf351e1825a2cee7"
class_hash = "0x796cff744d8a7c8056b9f07b614015bd0c4dfff1b3763ec46bb488029f9f6bc"
original_class_hash = "0x796cff744d8a7c8056b9f07b614015bd0c4dfff1b3763ec46bb488029f9f6bc"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/master_mind_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "master_mind::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x49b2b8f8fb3f3222b36d2911f08ef10162973d3c59c21dca52162f12fc036b3"
original_class_hash = "0x49b2b8f8fb3f3222b36d2911f08ef10162973d3c59c21dca52162f12fc036b3"
abi = "manifests/dev/abis/deployments/models/master_mind_models_moves_data.json"
name = "master_mind::models::moves::data"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "score"
type = "u8"
key = false

[[models.members]]
name = "color"
type = "ColorCombination"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x157d10e8c0021f2d7da9845db99521f82d8305ef03e2e2b9876ee269985bf2b"
original_class_hash = "0x157d10e8c0021f2d7da9845db99521f82d8305ef03e2e2b9876ee269985bf2b"
abi = "manifests/dev/abis/deployments/models/master_mind_models_moves_scores.json"
name = "master_mind::models::moves::scores"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "white_face"
type = "u32"
key = false

[[models.members]]
name = "black_face"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2b5a301cdda960645b3acaf585eea27852e72f819f939e395405bb30cf47978"
original_class_hash = "0x2b5a301cdda960645b3acaf585eea27852e72f819f939e395405bb30cf47978"
abi = "manifests/dev/abis/deployments/models/master_mind_models_moves_solution.json"
name = "master_mind::models::moves::solution"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "color"
type = "Codebreaker"
key = false
